# kAFL configuration for SDV/TDX guest setup
#
foobar: asd
qemu_path: $QEMU_ROOT/x86_64-softmmu/qemu-system-x86_64
ptdump_path: $LIBXDC_ROOT/build/ptdump_static
radamsa_path: $RADAMSA_ROOT/bin/radamsa

#qemu_append: init=/sbin/init root=/dev/vda1 rw hprintf=7 initcall_debug force_tdx_guest tdx_wlist_devids=pci:0x8086:0x29c0,acpi:PNP0501 nokaslr nopti mitigations=off mce=off
qemu_append: init=/sbin/init root=/dev/vda1 rw hprintf=4 lpj=300 force_tdx_guest tdx_wlist_devids=pci:0x8086:0x29c0,acpi:PNP0501 nokaslr nopti mitigations=off mce=off

qemu_base: -enable-kvm -machine kAFL64-v1 -cpu kAFL64-Hypervisor-v1,+vmx -smp 1 -no-reboot -display none -nodefaults -netdev user,id=mynet0 -device virtio-net,netdev=mynet0 -virtfs local,path=/tmp/kafl,mount_tag=tmp,security_model=mapped-file -device virtio-serial -device virtconsole,chardev=kafl_serial -device isa-serial,chardev=kafl_serial
qemu_extra:
